spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cryptocurrency?useSSL=false
    username: ladeiko_admin
    password: ladeiko123
    driver-class-name: com.mysql.jdbc.Driver

crypto:
  api: 'https://api.coinlore.net/api/ticker/?id='
  coins:
    - id: 90
      symbol: BTC
    - id: 80
      symbol: ETH
    - id: 48543
      symbol: SOL